paper_PE.pdf: paper_PE.tex references.bib
	latexmk -pdf paper_PE.tex

clean:
	rm -f paper_PE.aux paper_PE.dvi paper_PE.fdb_latexmk paper_PE.fls paper_PE.log paper_PE.out paper_PENotes.bib paper_PE.bbl paper_PE.blg paper_PE.pdf
